#!/bin/bash

echo "🚀 Quick Registration Fix"
echo "========================"

echo -e "\n1️⃣ First, let's check if it's a database schema issue:"
echo ""
echo "Run these commands on your Lightsail instance:"
echo ""
echo "ssh -i ~/.ssh/handreceipt-key-us-east-1 ubuntu@44.193.254.155"
echo ""
echo "# Check if the users table has all required columns"
echo "cd /opt/handreceipt/deployments/lightsail"
echo "sudo docker-compose exec postgres psql -U handreceipt -d handreceipt -c \"SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'users' ORDER BY ordinal_position;\""
echo ""
echo "# If the table is missing columns, run migrations:"
echo "sudo docker-compose exec app /app/backend migrate up"
echo ""
echo "# Or manually add missing columns:"
echo "sudo docker-compose exec postgres psql -U handreceipt -d handreceipt << 'EOF'"
echo "-- Add missing columns if they don't exist"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS rank VARCHAR(50);"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS unit VARCHAR(255);"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();"
echo "ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();"
echo "EOF"
echo ""
echo "# Check backend logs for the actual error:"
echo "sudo docker-compose logs app --tail=100 | grep -A10 -B10 'register\\|Register\\|CreateUser'"
echo ""
echo "# Restart the backend to ensure clean state:"
echo "sudo docker-compose restart app"
echo ""

echo -e "\n2️⃣ Alternative: Use this SQL to create a test user directly:"
echo ""
echo "sudo docker-compose exec postgres psql -U handreceipt -d handreceipt << 'EOF'"
echo "-- bcrypt hash for 'TestPassword123!'"
echo "INSERT INTO users (email, password_hash, first_name, last_name, rank, unit, status, created_at, updated_at)"
echo "VALUES ("
echo "  'test.user@handreceipt.com',"
echo "  '\$2a\$10\$RmZXMxVYbnNhTm9QZ2Z5UO3xJiIjLhQzNOazX.6ImhVz8QgPBpDhC',"
echo "  'Test',"
echo "  'User',"
echo "  'PVT',"
echo "  'Test Unit',"
echo "  'active',"
echo "  NOW(),"
echo "  NOW()"
echo ") ON CONFLICT (email) DO NOTHING;"
echo "EOF"
echo ""
echo "# Then you can login with:"
echo "# Email: test.user@handreceipt.com"
echo "# Password: TestPassword123!" 