# Example configuration file for HandReceipt backend
# Copy to config.yaml and update with your values

server:
  port: 8080
  environment: development

database:
  host: localhost
  port: 5432
  user: handreceipt
  password: your_db_password
  name: handreceipt
  
jwt:
  # REQUIRED: Set a secure secret key for JWT signing
  # In production, use environment variable HANDRECEIPT_JWT_SECRET_KEY
  secret_key: "your-secret-key-here-minimum-32-chars"
  access_expiry: 24h
  refresh_expiry: 168h
  
storage:
  type: minio  # or azure_blob
  endpoint: localhost:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  bucket_name: handreceipt