# HandReceipt Azure Configuration Override
# This file overrides settings in config.yaml for Azure deployment

# Server configuration
server:
  environment: "development"  # Changed from production to bypass ImmuDB requirement
  port: "8080"

# Database configuration - Use environment variables
database:
  host: "${HANDRECEIPT_DATABASE_HOST}"
  port: 5432
  user: "${HANDRECEIPT_DATABASE_USER}"
  password: "${HANDRECEIPT_DATABASE_PASSWORD}"
  name: "${HANDRECEIPT_DATABASE_NAME}"
  ssl_mode: "require"

# Storage Configuration - Use Azure Blob instead of MinIO
storage:
  type: "azure_blob"
  container_name: "handreceipt-photos"

# Disable MinIO
minio:
  enabled: false

# Disable ImmuDB temporarily (until we fix the connection)
immudb:
  enabled: false
  host: ""
  port: 0

# Security - Azure-specific CORS
security:
  cors_allowed_origins:
    - "https://handreceipt.com"
    - "https://www.handreceipt.com"
    - "https://handreceipt-backend.bravestone-851f654c.eastus2.azurecontainerapps.io"
    - "capacitor://localhost"
    - "http://localhost:8100" 