# HandReceipt Backend Production Configuration

# Server configuration
server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  environment: "production"
  tls_enabled: false
  cert_file: ""
  key_file: ""

# Database configuration
database:
  host: "postgres"  # Docker service name
  port: 5432
  user: "handreceipt"
  password: "cvOrf7fVpmyxvnkqeKOo5g=="
  name: "handreceipt"
  db_name: "handreceipt"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  migration_path: "./migrations"

# Auth configuration
jwt:
  secret_key: "9xr/uSKNDqOfSPkVOpujQUW3nzll5ykcT8nzu9W9Cvc="
  access_expiry: "24h"
  refresh_expiry: "168h"
  issuer: "handreceipt-go"
  audience: "handreceipt-users"
  algorithm: "HS256"
  refresh_enabled: true

# Auth session configuration
auth:
  session_secret: "9xr/uSKNDqOfSPkVOpujQUW3nzll5ykcT8nzu9W9Cvc="

# Ledger configuration - Using PostgreSQL for immutable ledger
ledger:
  type: "postgres"
  enabled: true

# ImmuDB configuration - DEPRECATED (replaced by ledger)
# immudb:
#   host: "immudb"  # Docker service name
#   port: 3322
#   username: "immudb"
#   password: "IoSzNPyRqFueVGhN/4rSgg=="
#   database: "defaultdb"
#   enabled: true

# MinIO configuration for document/photo storage
minio:
  endpoint: "minio:9000"  # Docker service name
  access_key_id: "handreceipt-minio"
  secret_access_key: "XQ/rycTvT6EbYfVLNQKEU1wk+GE="
  use_ssl: false
  bucket_name: "handreceipt"
  region: "us-east-1"
  enabled: true

# NSN service configuration
nsn:
  api_endpoint: ""
  api_key: ""
  cache_enabled: true
  cache_ttl: "24h"
  rate_limit_rps: 10
  timeout_seconds: 30
  retry_attempts: 3
  bulk_batch_size: 50
  publog_data_dir: "internal/publog"
  enabled: true

# Redis configuration (disabled for now)
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  enabled: false

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  filename: ""
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Security configuration
security:
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  password_require_symbol: false
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  cors_allowed_origins:
    - "https://handreceipt.com"
    - "https://www.handreceipt.com"
    - "capacitor://localhost"  # For iOS app
  rate_limit_enabled: true
  rate_limit_rps: 100 