# Hand Receipt Application Configuration Example

server:
  port: "8080"
  host: "0.0.0.0"
  environment: "development"

database:
  host: "localhost"
  port: 5432
  user: "handreceipt"
  password: "your_password_here"
  db_name: "handreceipt"
  ssl_mode: "disable"
  migration_path: "./migrations"

jwt:
  secret_key: "your-secret-key-here-change-in-production"
  access_expiry: "24h"
  refresh_expiry: "168h"

# Ledger configuration - Choose postgres or azure_sql
ledger:
  type: "postgres"  # or "azure_sql" for Azure deployment
  enabled: true

# ImmuDB configuration - DEPRECATED (replaced by ledger)
# immudb:
#   host: "localhost"
#   port: 3322
#   username: "immudb"
#   password: "immudb"
#   database: "defaultdb"
#   enabled: true

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket_name: "handreceipt"
  enabled: true

nsn:
  # API configuration (optional - for external NSN lookups)
  api_endpoint: ""
  api_key: ""
  
  # Caching configuration
  cache_enabled: true
  cache_ttl: "24h"
  
  # Rate limiting
  rate_limit_rps: 10
  timeout_seconds: 30
  retry_attempts: 3
  bulk_batch_size: 50
  
  # PUB LOG data directory - point to your extracted data
  publog_data_dir: "internal/publog"

redis:
  host: "localhost"
  port: 6379
  enabled: false

logging:
  level: "info"
  format: "json"
  output: "stdout"

security:
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  cors_allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_rps: 100 