# HandReceipt Azure Configuration Override
# This file overrides settings in config.yaml for Azure deployment

# Server configuration
server:
  environment: "production"
  port: "8080"

# Database configuration - Use environment variables
database:
  host: "${HANDRECEIPT_DATABASE_HOST}"
  port: 5432
  user: "${HANDRECEIPT_DATABASE_USER}"
  password: "${HANDRECEIPT_DATABASE_PASSWORD}"
  name: "${HANDRECEIPT_DATABASE_NAME}"
  ssl_mode: "require"

# Storage Configuration - Use Azure Blob instead of MinIO
storage:
  type: "azure_blob"
  container_name: "handreceipt-photos"

# Disable MinIO
minio:
  enabled: false

# Enable ImmuDB for immutable audit trail
immudb:
  enabled: true
  host: "${HANDRECEIPT_IMMUDB_HOST}"
  port: 3322
  username: "immudb"
  password: "${HANDRECEIPT_IMMUDB_PASSWORD}"
  database: "defaultdb"

# Security - Azure-specific CORS
security:
  cors_allowed_origins:
    - "https://handreceipt.com"
    - "https://www.handreceipt.com"
    - "https://handreceipt-backend.bravestone-851f654c.eastus2.azurecontainerapps.io"
    - "capacitor://localhost"
    - "http://localhost:8100" 