# config.azure.yaml

# HandReceipt Azure Configuration Override
# This file overrides settings in config.yaml for Azure deployment

# Server configuration
server:
  environment: "production"
  port: "8080"

# Database configuration - Will use environment variables
database:
  host: ""  # Uses HANDRECEIPT_DATABASE_HOST env var
  port: 5432
  user: ""  # Uses HANDRECEIPT_DATABASE_USER env var
  password: ""  # Uses HANDRECEIPT_DATABASE_PASSWORD env var
  name: ""  # Uses HANDRECEIPT_DATABASE_NAME env var
  ssl_mode: "require"

# Auth configuration - Override to ensure env vars are used
jwt:
  secret_key: ""  # MUST use HANDRECEIPT_JWT_SECRET_KEY env var
  
auth:
  session_secret: ""  # MUST use HANDRECEIPT_AUTH_SESSION_SECRET env var

# Storage Configuration - Use Azure Blob instead of MinIO
storage:
  type: "azure_blob"
  container_name: "handreceipt-photos"

# Disable MinIO
minio:
  enabled: false

# Ledger configuration - Using Azure SQL Database ledger tables
ledger:
  type: "azure_sql"
  enabled: true

# Azure OCR Configuration
ocr:
  type: "azure"
  endpoint: ""  # Uses AZURE_OCR_ENDPOINT env var
  api_key: ""   # Uses AZURE_OCR_KEY env var
  enabled: true

# AI Configuration - Azure OpenAI for DA 2062 enhancement
ai:
  provider: "azure_openai"
  endpoint: ""  # Uses AZURE_OPENAI_ENDPOINT env var
  api_key: ""   # Uses AZURE_OPENAI_KEY env var
  model: "gpt-4-turbo-preview"  # or your deployment name
  api_version: "2024-02-15-preview"
  max_tokens: 4000
  temperature: 0.1  # Low temperature for consistent DA 2062 parsing
  timeout_seconds: 30
  retry_attempts: 3
  cache_enabled: true
  cache_ttl: "24h"
  
  # DA 2062 Specific Settings
  da2062:
    confidence:
      ocr_weight: 0.4
      ai_weight: 0.4
      validation_weight: 0.2
      minimum_threshold: 0.7
      review_threshold: 0.85
    
    features:
      ai_parsing: true
      form_generation: true
      multi_line_grouping: true
      handwriting_support: true
      continuous_learning: false
    
    limits:
      max_requests_per_minute: 60
      max_tokens_per_day: 500000
      alert_threshold_usd: 50

# Security - Azure-specific CORS
security:
  cors_allowed_origins:
    - "https://handreceipt.com"
    - "https://www.handreceipt.com"
    - "https://handreceipt-backend.bravestone-851f654c.eastus2.azurecontainerapps.io"
    - "https://handreceiptprodstorage.z20.web.core.windows.net"  # Azure Storage static website
    - "https://handreceipt-prod-frontend.azureedge.net"  # Azure CDN endpoint
    - "capacitor://localhost"  # iOS app
    - "http://localhost:8100"  # Development 