# HandReceipt Backend Configuration

# Server configuration
server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  environment: "production"
  tls_enabled: false
  cert_file: ""
  key_file: ""

# Database configuration
database:
  host: "postgres"  # Using Docker service name
  port: 5432
  user: "handreceipt"
  password: "cvOrf7fVpmyxvnkqeKOo5g=="
  db_name: "handreceipt"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  migration_path: "./migrations"

# Auth configuration
jwt:
  secret_key: "9xr/uSKNDqOfSPkVOpujQUW3nzll5ykcT8nzu9W9Cvc="
  access_expiry: "24h"
  refresh_expiry: "168h" # 7 days
  issuer: "handreceipt-go"
  audience: "handreceipt-users"
  algorithm: "HS256"
  refresh_enabled: true

# Auth session configuration
auth:
  session_secret: "9xr/uSKNDqOfSPkVOpujQUW3nzll5ykcT8nzu9W9Cvc="

# ImmuDB configuration - Using as immutable ledger instead of QLDB
immudb:
  host: "immudb"  # Using Docker service name
  port: 3322
  username: "immudb"
  password: "IoSzNPyRqFueVGhN/4rSgg=="
  database: "defaultdb"
  enabled: true

# MinIO configuration for document storage
minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  use_ssl: false
  bucket: "handreceipt-photos"
  enabled: true

# Storage Configuration (for Azure Blob Storage)
storage:
  type: "minio"  # Can be "minio" or "azure_blob"
  # Azure Blob Storage settings (used when type is "azure_blob")
  connection_string: ""  # Set via HANDRECEIPT_STORAGE_CONNECTION_STRING env var
  container_name: "documents"  # Default container name
  account_name: ""  # Parsed from connection string

nsn:
  api_endpoint: ""
  api_key: ""
  cache_enabled: true
  cache_ttl: "24h"
  rate_limit_rps: 10
  timeout_seconds: 30
  retry_attempts: 3
  bulk_batch_size: 50
  publog_data_dir: "internal/publog"

redis:
  host: "redis"  # Using Docker service name
  port: 6379
  password: ""
  db: 0
  enabled: false

logging:
  level: "info"
  format: "json"
  output: "stdout"
  filename: ""
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

security:
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  password_require_symbol: false
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  cors_allowed_origins:
    - "capacitor://localhost"       # For iOS app
    - "http://localhost:3000"       # For local development
    - "http://localhost:5173"       # For Vite development server
    - "http://localhost:8100"       # For Ionic serve
    - "https://handreceipt.com"     # Production web
    - "https://www.handreceipt.com" # Production web with www
  rate_limit_enabled: true
  rate_limit_rps: 100 