# config.local.yaml

# HandReceipt Backend Local Development Configuration

# Server configuration
server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  environment: "development"
  tls_enabled: false

# Database configuration
database:
  host: "localhost"  # For local development
  port: 5432
  user: "handreceipt"
  password: "cvOrf7fVpmyxvnkqeKOo5g=="
  name: "handreceipt"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  migration_path: "./migrations"

# Auth configuration
jwt:
  secret_key: ""  # REQUIRED: Set via HANDRECEIPT_JWT_SECRET_KEY env var
  access_expiry: "24h"
  refresh_expiry: "168h"
  issuer: "handreceipt-go"
  audience: "handreceipt-users"
  algorithm: "HS256"
  refresh_enabled: true

# Auth session configuration
auth:
  session_secret: ""  # REQUIRED: Set via HANDRECEIPT_AUTH_SESSION_SECRET env var

# Ledger configuration - Disabled for local development
ledger:
  type: "postgres"
  enabled: false

# MinIO configuration - Disabled for local development
minio:
  enabled: false

# Storage Configuration - Disabled for local development
storage:
  type: "minio"
  enabled: false

nsn:
  api_endpoint: ""
  api_key: ""
  cache_enabled: false
  cache_ttl: "24h"
  rate_limit_rps: 10
  timeout_seconds: 30
  retry_attempts: 3
  bulk_batch_size: 50
  publog_data_dir: "internal/publog"

redis:
  enabled: false

logging:
  level: "debug"
  format: "text"
  output: "stdout"

security:
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  password_require_symbol: false
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  cors_allowed_origins:
    - "*"  # Allow all origins for local development
  rate_limit_enabled: false

# AI Configuration - Azure OpenAI for DA 2062 enhancement (disabled for local)
ai:
  provider: "azure_openai"
  endpoint: "${AZURE_OPENAI_ENDPOINT}"
  api_key: "${AZURE_OPENAI_KEY}"
  model: "gpt-4-turbo-preview"
  api_version: "2024-02-15-preview"
  max_tokens: 4000
  temperature: 0.1
  timeout_seconds: 30
  retry_attempts: 3
  cache_enabled: false  # Disabled for local
  cache_ttl: "24h"
  
  # DA 2062 Specific Settings
  da2062:
    confidence:
      ocr_weight: 0.4
      ai_weight: 0.4
      validation_weight: 0.2
      minimum_threshold: 0.7
      review_threshold: 0.85
    
    features:
      ai_parsing: false  # Disabled for local
      form_generation: false
      multi_line_grouping: false
      handwriting_support: false
      continuous_learning: false 