# config.azure.yaml

# HandReceipt Azure Configuration Override
# This file overrides settings in config.yaml for Azure deployment

# Server configuration
server:
  environment: "production"
  port: "8080"

# Database configuration - Will use environment variables
database:
  host: ""  # Uses HANDRECEIPT_DATABASE_HOST env var
  port: 5432
  user: ""  # Uses HANDRECEIPT_DATABASE_USER env var
  password: ""  # Uses HANDRECEIPT_DATABASE_PASSWORD env var
  name: ""  # Uses HANDRECEIPT_DATABASE_NAME env var
  ssl_mode: "require"

# Storage Configuration - Use Azure Blob instead of MinIO
storage:
  type: "azure_blob"
  container_name: "handreceipt-photos"

# Disable MinIO
minio:
  enabled: false

# Ledger configuration - Using Azure SQL Database ledger tables
ledger:
  type: "azure_sql"
  enabled: true

# Azure OCR Configuration
ocr:
  type: "azure"
  endpoint: ""  # Uses AZURE_OCR_ENDPOINT env var
  api_key: ""   # Uses AZURE_OCR_KEY env var
  enabled: true

# Security - Azure-specific CORS
security:
  cors_allowed_origins:
    - "https://handreceipt.com"
    - "https://www.handreceipt.com"
    - "https://handreceipt-backend.bravestone-851f654c.eastus2.azurecontainerapps.io"
    - "https://handreceiptprodstorage.z20.web.core.windows.net"  # Azure Storage static website
    - "https://handreceipt-prod-frontend.azureedge.net"  # Azure CDN endpoint
    - "capacitor://localhost"  # iOS app
    - "http://localhost:8100"  # Development 