# HandReceipt Backend Configuration

# Server configuration
server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  environment: "development" # "development", "production"
  tls_enabled: false
  cert_file: ""
  key_file: ""

# Database configuration
database:
  host: "localhost"
  port: 5432
  user: "handreceipt"
  password: "handreceipt_password"
  db_name: "handreceipt"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  migration_path: "./migrations"

# AWS QLDB configuration
qldb:
  ledger_name: "handreceipt-ledger"
  region: "us-east-1"
  # Tables to create if they don't exist
  tables:
    - "ItemCreations"
    - "TransferEvents"
    - "StatusChanges"
    - "VerificationEvents"
    - "CorrectionEvents"

# Auth configuration
jwt:
  secret_key: "your-super-secret-jwt-key-change-this-in-production"
  access_expiry: "24h"
  refresh_expiry: "168h" # 7 days
  issuer: "handreceipt-go"
  audience: "handreceipt-users"
  algorithm: "HS256"
  refresh_enabled: true

immudb:
  host: "localhost"
  port: 3322
  username: "immudb"
  password: "immudb"
  database: "defaultdb"
  enabled: false

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket_name: "handreceipt"
  region: "us-east-1"
  enabled: false

nsn:
  api_endpoint: ""
  api_key: ""
  cache_enabled: true
  cache_ttl: "24h"
  rate_limit_rps: 10
  timeout_seconds: 30
  retry_attempts: 3
  bulk_batch_size: 50

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  enabled: false

logging:
  level: "info"
  format: "json"
  output: "stdout"
  filename: ""
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

security:
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  password_require_symbol: false
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  cors_allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_rps: 100 